---
# meta file for roles/backups
dependencies:
  - role: postgres
  - role: auth
  - role: docmost
  - role: heyform
  - role: mealie
  - role: nextcloud
  - role: paperless
  - role: satisfactory
  - role: woodpecker
