beszel_local_agent_token: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  34386634633632336462356461626539363830393461626338633733383566303534373338663239
  3239343436323936313533646637643334613162353663610a636331323366313136393630363637
  38326338326561366632383261633133653662623865323061363633366331616435656330663265
  3536323833333561370a613035373765623232626539633033396132653066313466313135326639
  32613235396439373062396236636237313166323661633836646634653366313836666537306332
  3938336366633865386665336534373164333763396337323462
