---
donetick_db_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  38616561666331386236343032613636356431393530396364376264653863383037616132633661
  6334623439356136666233646138373036336563376234360a663533303931633736303734353033
  65326332643366636630653239343035306539313436393337616337363938666539626137333636
  6531353138363636610a653536663134656631316161373134663063663737303862396135623231
  63623030373265353533356436623935326638343862343331383162363131653738613236643037
  6561396539656464643036613035333962643831626664376632
donetick_jwt_secret: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  30326362353633633933663130623437383430613734383736396439626466633831363962306238
  3336353933376336366534623864616339326138333539610a393438363439633530636438383634
  61646132343033356161663437663561623766383538353663376238663464383461303032623031
  6561653966636562640a646165633230303761343662653138353130326461643333313933633133
  37623630386133656339373535313132363538326534376662373937633865313434613561336538
  37666130333637336637353238633064386332326664343335653366353337653962623065343662
  64373037333066666339393134633836633037373338396138376436313230663261363939316239
  36626466383936363765
donetick_oidc_client_id: 91efc1b1-722a-4b18-bd19-4106c65afd82
donetick_oidc_client_secret: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  39373563373336353764656138373737333136313838653936376330346537636631336163656331
  6562623439353966613533343034346438373430386134650a306338656130616137343464643739
  37613532306361313762636231326436633664643034623466363234396233376461336662303838
  3864613733386635360a356236663336386433633663663639376538623634643335623564393238
  39366464633737643564613034376234663139656533613336343965653563633066343461336462
  3863636565323431346365646430313931393234356339343232
