---
media_manager_db_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  65623565326631303433346138333535323666386365653637353161326635616565336633363733
  3534333831386230353939643532636635663463323538320a663562636134646335386462336531
  66336261336131396535633334326364343163373435313437636433383565653430623738663033
  6339393561646364350a356563343734333937626136633139626163636263373136353162326434
  64633337333766656536636564633966636138383238386239626435383337356563386165356238
  66363830343462353061626432376664396562326632356238666162633962356130353532373634
  64343538343137636330393639393938343164346537323536363065373131643439306566636461
  62613366636335633632
media_manager_secret: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  66393030646135643033383630643630346630366635656236333638336265613338653463303262
  3730633232616661316265316661316462376366353931330a653631656537336534323236633365
  62326338353936623738356236303131633339653764333930613461303834386438353662653330
  6563363536346365320a313132653438333466326363663262646638613263333832316665616137
  64313432353265303262326230343534373866623438356635653730323331346236306138333838
  63323461343031353433366332613237396133666363363435366131373338306332346666373235
  34353339336535343237333435383732383961346563653566646565646635666432653532376236
  32323632616632643465
media_manager_auth_client_id: bdf61119-65c4-4c17-b8a5-d160140206e3
media_manager_client_secret: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  36616435363666663564393938343230306661373464303538346637333966663437393336663566
  6265646437356263346636343237323033343461303135640a653132333265396232373364343062
  32386537323934373335646466663163343138643962343836376364343537383261623034623465
  3935303238366565620a363035393362333438383136646631343630643466336239656165663765
  66633565356333653335613464396331393864643736373939366563383832653337636164393666
  3735393835666261326133316433326365626233626635366163
media_manager_prowlarr_api_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  64663138323233653135643465656161663933383534613034303133346138336532623631346635
  3537336364643736333133303031333832313336356165650a353038363964653765653766336563
  32643637633861376138626637323335633866363866383431636564313038323435303761303036
  6632336635303766640a316663656634663635336232306261346561393435626131666366373438
  32623530656238326131613637366431303330666236663639373835643266366564393638616566
  6564663839326233303565376366313431646664386136616261
