---
# Fixed Ports (default for usability/simplicity)
mariadb_port: 3306
teamspeak_voice_port: 9987
satisfactory_server_game_port: "28001"
satisfactory_server_messaging_port: "28000"

# Application Ports
postgres_port: 27802
auth_lldap_port: 27900
auth_authelia_port: 27901

wakapi_port: 28943
# 28944
paperless_port: 28945
docmost_port: 28946
search_port: 28947
# 28949
mealie_port: 28949
nextcloud_port: 28950
nextoffice_onlyoffice_port: 28951
nextcloud_whiteboard_port: 28952
woodpecker_port: 28953
yamtrack_port: 28954
# 28955
romm_port: 29156
stirlingpdf_port: 28957
# 29158
navidrome_port: 29159

pocketid_port: 29000
beszel_port: 29001

teamspeak_file_port: 30033

jellyfin_port: 30212
seedbox_slskd_port: 30213
seedbox_qbittorrent_port: 30214
arr_sonarr_port: 30215
arr_radarr_port: 30216
arr_prowlarr_port: 30217
arr_bazarr_port: 30218
arr_jellyseerr_port: 30219
arr_lidarr_port: 30220
# 30221
# 30222
donetick_port: 30223

heyform_port: 30300

seedbox_promex_port: 44401
