---

teamspeak_db_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  32343032363236313338356361363431663665613766616634333939653335623066393962663334
  3238373266306632613463626133616163373230333865390a636465393231653937333137383963
  61666265663466326435613562613337323530386538616530323536613932326338366439373665
  3665313662363538320a326531626463653766333138313264623837636434666338363739343164
  66316138306263333739313439613863653639653537376537616461343731623034353466386161
  65373362323133373932636362383537646439636132303535336330623332363537373834313865
  393866306365373937326639323630613730
teamspeak_webquery_api_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  63323535633034303934376132343265653438653638353134316531623738373634356132663966
  6162313464356232343934666438663436316434623232350a333033663732333033343238376432
  35306438626132646536303034306331303732643631313134623565356361376334666535653235
  6164303463663433640a303632653665386166383934326539326463306563383134346461353335
  32343364383036333562656435313763363064363362316630323338363930303239633433636237
  6263653063663032303139343435373137366432393235353866
teamspeak_bot_discord_token: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  35343335633334353637326436356339353939653063356539633538373765616366646162653035
  6136323664333165663866326264363965633963623032630a346239336666393965323837323035
  63376433633434346263633561373666616262303935363431333836336431363139356364643366
  3339633232376537610a393466373731623936613533656431353032633530366236376238353864
  39343039363334363561336431373732316136343132653637383430376131643033613563373666
  31346230333631613531626634663834653535383865623239336136366334363961386333643433
  33343632343835313334666436323161303633666261353664636333623866643066353062663930
  38323534366162306633
