---
yamtrack_domain: "track.{{ root_domain }}"
yamtrack_secret: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  32643461643335353866626431346433383934616363393663643363353431316538356535303166
  3236326436306335313537303932333638633036323538640a333162383438393337646539636465
  65316136643036346439306532323532643834306666346461636435323937316339623364656431
  6639353332666137620a303134613330313932313965363664646366316135326336316564656133
  35303433353233326430363164633833313261326634623461353264393030353263396666303634
  6337326662613237663930313664323864356330346566346635
yamtrack_auth_provider_authelia: 01k0catx8c1hg40cdbsxjkny3g
yamtrack_auth_provider_pocketid: 01kdgr3rjc6qn308d8whna15yy
yamtrack_auth_client_id: 1003ae3d-0a1a-4eea-8337-3bf00e6a210e
yamtrack_auth_client_secret: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  61366362353433333665633238363530323661366161356331633662353838623030373464333331
  6338393464623565623066646434326363323739366435340a356631333266316336316366613564
  39646232316137313334343162353536643938313533383630633362313137636261336639663530
  3134633531363461340a393563356264313066316661333635313432613364386636393061626431
  30383633386165616639636436653834363535373533373662333838353531383832613236636363
  3962663039313666346161386630363731353162373530376337
