---
# vars for cronjob
cronjob_complete_command: >-
  '{{ cronjob_script_path }}'
  --avatar '{{ cronjob_notification_avatar }}'
  --name '{{ cronjob_notification_as }}'
  --webhook-id '{{ notifications_webhook_id }}'
  --webhook-token '{{ notifications_webhook_token }}'
  {% if cronjob_dont_notify_if is defined %} --dont-notify-if '{{ cronjob_dont_notify_if }}' {% endif %}
  --always-ping {{ cronjob_always_ping }}
  --command '{{ cronjob_command }}'
